### ISSUE TITLE
[refactor] branching out the simulated demo

### ISSUE THREAD

**Issue by wangchongyu** [XtraBros/smart-itinerary-planner#29]
Create a separate branch for the simulated demo. This branch will have the same features as the live demo, but the user's movement will be simulated.

**Comment by zwzac** [comment]
opened branch [refactor/29/sentosa-simulation](https://github.com/XtraBros/smart-itinerary-planner/tree/refactor/29/sentosa-simulation) based on updated sentosa demo

Supported features:
1) Navigation view + simulated user movement
2) AI prompt via "Discover nearby" and "Hotel" buttons
3) Automatic promotion message when AI assistant mentions POIs with registered events on the events database ( Example: Assistant suggests SkyHelix to user, and SkyHelix have sale event registered on db, assistant will automatically follow up with a promo message)


All other requirements in the 1st demo are supported, and major bugs have been fixed for the simulation.
