### ISSUE TITLE
[fix] Sometimes clicking the top right corner doesn't retrieve the current location

### ISSUE THREAD

**Issue by wangchongyu** [XtraBros/smart-itinerary-planner#31]

**Comment by zwzac** [comment]
Issue is not due to code error, but due to connection to host website being insecure.
Error message:
[blocked] Access to geolocation was blocked over insecure connection to (url)

**Comment by acekillersg** [comment]
> Issue is not due to code error, but due to connection to host website being insecure. Error message: [blocked] Access to geolocation was blocked over insecure connection to (url)

@wangchongyu @zwzac I think we always need to use HTTPS to visit the website, then this problem will not occur.
