### ISSUE TITLE
[fix] Location-Based Promotional Messaging

### ISSUE THREAD

**Issue by wangchongyu** [XtraBros/smart-itinerary-planner#44]
When the user enters a predefined range (e.g., within 20 meters) of a specific location, the system detects that the user is near the targeted area. Upon detecting that the user is within this range:

AI sends a promotional message relevant to that location:

Scenario A: If the user currently has the AI chatbot dialogue window closed:
* The system displays a notification bubble to prompt the user to click and view the promotional message.
* The bubble serves as a visual cue, once the user clicks the bubble and opens the dialogue window to check the message, removes the bubble automatically

Scenario B: If the user already has the AI chatbot dialogue window open:
* The system sends the promotional message directly in the dialogue window.
* there is no need to display an additional bubble.

**Comment by zwzac** [comment]
Disabled all promo messages except location based messages for POIs within 500m radius (detected automatically when tracking the user location to display the POIs in "List" tab)
